services:
    nats:
        image: nats
        command:
            -   '-js'
    orthanc:
        image: local/orthanc
        build: .
        environment:
            VERBOSE_ENABLED: "true"
            ORTHANC__SSL_ENABLED: "true"
            ORTHANC__SSL_CERTIFICATE: "/ssl/keyAndCert.pem"

            ORTHANC__OVERWRITE_INSTANCES: "true"

            ORTHANC__PYTHON_VERBOSE: "false"
            ORTHANC__HTTP_PORT: "8042"
            ORTHANC__PYTHON_SCRIPT: "/python/entry_point.py"

            ORTHANC__REGISTERED_USERS: |
                {"demo": "demo"}

            NATS_URL: nats://nats
        depends_on:
            -   nats
        ports:
            - "127.0.0.1:4242:4242"
            - "127.0.0.1:8042:8042"
