import re

import requests

from orthanc_ext.orthanc import OrthancApiHandler

orthanc = OrthancApiHandler()


def test_change_type_list_should_be_complete():
    source = get_source_file("OrthancPluginChangeType")
    events = re.findall(f'sdk_OrthancPluginChangeType.tp_dict, "([A-Z_]+)"', source)

    assert len(events) > 16
    for event in events:
        assert orthanc.ChangeType.__dict__.get(
            event) is not None, f"'{event} should be added on {orthanc.ChangeType}"


def test_resource_type_list_should_be_complete():
    source = get_source_file("OrthancPluginResourceType")
    events = re.findall(f'sdk_OrthancPluginResourceType_Type.tp_dict, "([A-Z_]+)"', source)

    assert len(events) > 4
    for event in events:
        assert orthanc.ResourceType.__dict__.get(
            event) is not None, f"'{event} should be added on {orthanc.ResourceType}"


def get_source_file(type_under_test):
    resp = requests.get(
        f'https://hg.orthanc-server.com/orthanc-python/raw-file/tip/Sources/Autogenerated/sdk_{type_under_test}.impl.h')
    resp.raise_for_status()
    return resp.text
