# Generated at 2021-07-09T11:48:26.006873Z
# from https://hg.orthanc-server.com/orthanc-python/raw-file/tip/Sources/Autogenerated/sdk_OrthancPluginResourceType.impl.h and
# from https://hg.orthanc-server.com/orthanc-python/raw-file/tip/Sources/Autogenerated/sdk_OrthancPluginChangeType.impl.h

import enum

class ResourceType(enum.Enum):
    PATIENT = 0
    STUDY = 1
    SERIES = 2
    INSTANCE = 3
    NONE = 4
    UNKNOWN = 999

class ChangeType(enum.Enum):
    COMPLETED_SERIES = 0
    DELETED = 1
    NEW_CHILD_INSTANCE = 2
    NEW_INSTANCE = 3
    NEW_PATIENT = 4
    NEW_SERIES = 5
    NEW_STUDY = 6
    STABLE_PATIENT = 7
    STABLE_SERIES = 8
    STABLE_STUDY = 9
    ORTHANC_STARTED = 10
    ORTHANC_STOPPED = 11
    UPDATED_ATTACHMENT = 12
    UPDATED_METADATA = 13
    UPDATED_PEERS = 14
    UPDATED_MODALITIES = 15
    JOB_SUBMITTED = 16
    JOB_SUCCESS = 17
    JOB_FAILURE = 18
    UNKNOWN = 999