name: "Integration Tests"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    name: "Verify sync entrypoint example"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set up environment"
        run: docker compose up -d --wait
      - name: "Test server"
        run: docker compose logs orthanc | grep "orthanc version retrieved"
      - name: "Tear down Docker Compose"
        if: always()
        run: docker-compose down

